var rule = {
  title: '电影100',
  host: 'https://www.dianying101.xyz/',
  url: '/index.php/vod/show/fyfilter.html',
  searchUrl: '/index.php/new_search/search/wd/**/page/fypage.html?wd=**',
  searchable: 2,
  quickSearch: 0,
  filterable: 1,
  filter: 'H4sIAAAAAAAAA+2ba1MTSRSG/0s+u5UZLpnRb97v97tbloWa2rVWsQpxqyzLKpSLgHJRkYggoBJAJRLEG4GEP5OeSf7FTrqTnvccXDNZ0Vp35+O8z0vP5E2mp0/P4WakriGy6debkT/iNyKbIu7Cshi/F9kQaW66EsfjP5suX49LY7Mni87ZYvtsSfYOIrc2KNWdSImembJ66WK0PqaRGM3mMzOEeuetUGduxs31U+rDRJISQ6PixCuKTP+EA2mKYMDP8xTV+2iR/VWjP2Dnx/zyMKVW5NbZElfZecxp7/Sz08dBsiskV331wuWma9eiSor68c48EEvLxKIksPTOu9nX1CIlsHQvlK/Kt0gJLO2pwvM2apESWG7nik9z1CIl3+J8+CSmholFSWBJTedzk9QiJbB0P8lneqhFSmBp73XuPKUWKaGls9DzjllKEljuzLnDD6hFSmC5Pei0sU8kJd8i3n4UmRSxKAksybv8a1QSWIbH/B9a2SIlsAzed9qYRUpgGZgqvKTftJLA0t8lBmguSgJL76w7xC5XSsSSz45xiyeBRd8LvkVKYOl6WBx5RS1S8i35lcnC2zSxKMm3FFYHvXPT+0hKUXqvjqXF/Qzcq5XjIPeqmJopjnSV1aaWeFNUKf5VFKdHvFkGHUrBLyftLOXIGFKBMbzJbTRLxpAK/B4TSWdsDh1KgTQ+9oq+BDqUEsV5xx1IuT0jxFQRwTfwTuTuibfkkrUIvnsL7KqVAo7eOdGZJg6pwOTiPQvoGEoBx4Nx0fmZOKQC2eQWvS9FdL/KZ56ShEAHtzfv0zMqBR0v2FUrBR2P14zxmI4xkvFOTBxSAcdw2suen6giEp/onRTPnjOfEsF3/7WYvU1MUgFHx4DKg5gqIvxec5/Yp1MKOD699y6TOKQCjvRK6WG+5jtBHefJZOmupFemRfC9mC3F8yhJfBURfGMThbZF7zFOfBURfI+S+ZVpZ36IXyXo4O5Li8w08UkFHYnis3HqKCk4f04691a9xImpIsL0t9rhZhPOMJlYtAi+z0tFek1Kgbnl1ZzzLOklxD4j6nB9culDLk4qbEpdep9fzsKUWjkOMqXWGd5SS2nRG/GmlqgUgDZw2oC0ntN6pHWc1iE1OTWRGpwaQM2NjHoCUJtTG6nFqYU0xmkMKc/KxKxMnpWJWZk8KxOzMnlWJmZl8qxMzMrkWZmYlcGzMjArg2dlYFYGz8rArAyelYFZGTwrA7MyeFYGZmXwrAzMyuBZGZiVwbMyMCuDZ2X4WZkbN9KspADU5tRGanFqIY1xGkPayGkj0gZOG5DWc1qPtI7TOqQmpyZSg1PMyuZZ2ZiVzbOyMSubZ2VjVjbPysasbJ6VjVnZPCsbs7J5VjZmZfOsbMzK5lnZmJXNs7IxK4tnZWFWFs/KwqwsnpWFWVk8KwuzsnhWFmZl8awszMriWVmYlcWzsjAri2dlYVYWz8rCrGI8qxhmFeNZxTCrGM8qhlnFeFYxzCrGs/IEfMwW5lOF2Tb/MauPA1Uuo1nPXznB5abm36JlCdbv3FGW9Nr73RR3lCWoXLijLEHlwh1lCdYc4m07vVIlkTVHKuHM98Gao3IcJIzNevR4a2u8JbpZky2MbNFkKyNbNdnGyDZNtjOyXZMdjOzQZCcjOzXZxcguTXYzsluTPYzs0WQvI3s12cfIPk32M7JfkwOMHNDkICMHNTnEyCFNDjNyWJMjjBzR5CgjRzU5xsgxTY4zclyTE4yc0OQkIyc1OcXIKU1OM3JakzOMnNHE+GUjYyUFbwGn/6HIDPi3gD4Ocgs4iY/FxPuyev5GtPXSlTjUEZmMkx7y6e+XWq9BHT/fIbq7fHrx6vXzTc3nrl242gJjFFYfOGMTbnuqmJj1vS3xC/Hm1nPsT87eOrshUhdbr+3o0mbIypuyWtquJdvRFPlzu9qLJrS+bv32eT2n0zFRVvVOpCfVts9bfYfW6Z91B7voiaQElsFxd45teUqppk25wuCzQj/doVUSnGjyuRilu6JKqmkP0RnLON1P6ChSCrb7Vxml+oaySHtpv6fXIiVqSS6usSQX4TuayuVX6La0knD7dUJ0j9JRpIT34DuRGiQWJcGJRnudkQw9kZQw3QWxmmDplqS/KfLLli9V+d9347T6lqa6P4lDKuF2RbhdEW5XMPpdtyt+sqIkkRV9iTV1iVbD4gVIWLyExUtYvPyD4sVet16aoQ8iuwAViv+AcTOvRfax23MXKhT/MZBfmfbX/SXUuH7FS4C3+AHaSwI0QARpL6m+jg9QSAWobwI0YwToHQnQmROgvcRJ3S90j1OLlGprxqjeGBKg0yJIY0jHqvsmSS1Sqq0FqHp/T3FiMb9EqyQl1dTq4n0878ai1aOUSLtEtTatr3Xm/FwdKNX7MAJ0oFTtB6ne5xK4R6XvE+8skcr37Aqp2vMRtFPjR/Zh/At7FsKOhLDED0v8sMT/phJ/HUp3b/5e41ASzMBrPouSwvI/LP/D8v9/XP7Xm1D+f1ulLZfz7vJKoYe+2UHAX4p8wY6ALNu9ifFLdgA1VVfFth53hr6QVFJN7+YKHQti4CUfSKtQmbAtkHJBXVHBODbh/RL4iFrFl2ifxUta8CqppuI7wNvdAHsFQf6J5CubEj+wyFyHf1GoXmR+pYQMF/vhYj9c7K//Yj9cm4Zr03Bt+h9am976C0WGddLoPQAA',
  filter_url: '{{fl.地区}}{{fl.排序}}{{fl.剧情}}{{fl.类型}}{{fl.语言}}{{fl.字母}}/page/fypage{{fl.年份}}',
  filter_def: {28:{类型:"id/28"},24:{类型:"id/24"},26:{类型:"id/26"},31:{类型:"id/31"},},
  headers: {'User-Agent': 'MOBILE_UA',},
  class_parse: '.myui-header__menu li.hidden-sm:gt(0):lt(7);a&&Text;a&&href;/(\\d+).html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  double: true,
  推荐: 'ul.myui-vodlist.clearfix;li;a&&title;a&&data-original;.text-overflow&&Text;a&&href',
  一级: '.myui-vodlist li;a&&title;a&&data-original;.text-overflow&&Text;a&&href',
  二级: {
    title: '.myui-content__detail .title--span&&Text;.score&&Text',
    img: '.myui-content__thumb .lazyload&&data-original',
    desc: '.data:eq(0)&&Text;.text-muted.hidden-xs:eq(1)--a&&Text;.text-muted.hidden-xs:eq(0)--a&&Text;.myui-content__detail p.data:eq(2&&Text;.myui-content__detail p.data:eq(3)&&Text',
    content: '.sketch.content&&Text',
    tabs: '.nav-flex&&li',
    lists: '.myui-content__list:eq(#id) li',
  },
  搜索: '#searchList li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href;.detail&&Text',
}
